production:
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  bucket: <%= ENV['S3_BUCKET_NAME'] %>
  region: 'us-west-2'
  folder: 'attachments'
  endpoint: 's3.amazonaws.com'
  secure: false
  private: false
  expires: 1000
  proxy: false
  thumb_folder: 'tmp'

development:
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  bucket: <%= ENV['S3_BUCKET_NAME'] %>
  region: 'us-west-2'
  folder: 'attachments'
  endpoint: 's3.amazonaws.com'
  secure: false
  private: false
  expires: 1000
  proxy: false
  thumb_folder: 'tmp'

# Uncomment this to run plugin tests with standart redmine script
# test:
#   access_key_id:
#   secret_access_key:
#   bucket:
